---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1rft6er4pj4dk7wf887pgsalekxjl6z34sc96lfkz9mkc70qxm9xqhfqhvc"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1rft6er4pj4dk7wf887pgsalekxjl6z34sc96lfkz9mkc70qxm9xqhfqhvc"
stores:
  yaml:
    indent: 2
