apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:11D5anUwY7vTBQ==,iv:egazEJckcsBwdkFWpfKI2Qkxetb7U/2FEmpzUOOvq18=,tag:81izXHZNctdpCSXe4EIjaw==,type:str]
  SECRET_ALERTMANAGER_CHAT_ID: ENC[AES256_GCM,data:XFny0zr7OoQLxw==,iv:WQT+q2C62gHs60PWJJhTy/C6wIigTsTlSJJOjhH65Fk=,tag:N/hNnCA0lmHsvmfSgBf7mA==,type:str]
sops:
  age:
    - recipient: age1rft6er4pj4dk7wf887pgsalekxjl6z34sc96lfkz9mkc70qxm9xqhfqhvc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYjc4ZGhKc09VdnpvRVFj
        VDFQWVlLN0ppYWJOVVVqUFAvRWpLc3ZxeldNCnFJMzJnTHFKOXh6aGlub0ZyeUpw
        U1I1L0ExQUNtc3ZEdXNMTHZUeVhkNDQKLS0tIEtpbVZsUGtlaFY5cytGWjRvZHBx
        L2tVQTYzV0NXR1dFUC9Ncnd6QkhkWEUKV08XhoRpajnaCxWEJnIfND1kGJP6Vt3u
        Ss6hGb6eIy9yJs6D34WfsHtzGqrmhPEeJczF9YXoNHsAqxySfovYdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-20T00:38:26Z"
  mac: ENC[AES256_GCM,data:2N2TcQ4TrJcmlRklr7aQDxfSbWIDAVqDzTN2xnKNJsmIM8Nv8d9ibipRdq1tDiFm37ESHETwkxuyje03DEQq212kN0L1LCIiz5CTwJ/gf7izvUqJZVUlJQCgDsozOMlsDd7tQuQsbs/Arfopdn30mOwvA8Tin5wCL6knW75JfOc=,iv:DBNwseqiVj1Bk0sGEruMiNHg0XufHw1INm+N7BS0pnI=,tag:eQMoTvzoo954B/3cwpl9gg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
