apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:11D5anUwY7vTBQ==,iv:egazEJckcsBwdkFWpfKI2Qkxetb7U/2FEmpzUOOvq18=,tag:81izXHZNctdpCSXe4EIjaw==,type:str]
  SECRET_ALERTMANAGER_CHAT_ID: ENC[AES256_GCM,data:f+AgnjlNXkTVtw==,iv:qV5Lyvi0K675ALp6LcktQZSBAu78klgjRwtKqSquZzk=,tag:0wK3X956FudG7blNYKe+3A==,type:str]
sops:
  age:
    - recipient: age1rft6er4pj4dk7wf887pgsalekxjl6z34sc96lfkz9mkc70qxm9xqhfqhvc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYjc4ZGhKc09VdnpvRVFj
        VDFQWVlLN0ppYWJOVVVqUFAvRWpLc3ZxeldNCnFJMzJnTHFKOXh6aGlub0ZyeUpw
        U1I1L0ExQUNtc3ZEdXNMTHZUeVhkNDQKLS0tIEtpbVZsUGtlaFY5cytGWjRvZHBx
        L2tVQTYzV0NXR1dFUC9Ncnd6QkhkWEUKV08XhoRpajnaCxWEJnIfND1kGJP6Vt3u
        Ss6hGb6eIy9yJs6D34WfsHtzGqrmhPEeJczF9YXoNHsAqxySfovYdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-20T00:49:30Z"
  mac: ENC[AES256_GCM,data:OcZbYnHqnO7HSoLee8mk3K7rHGtABaF9PBDOWpcm3DJpFglXbtEK0VvulmZ8puLNfbFs/4rAPtEn7YZqKkQ2tLXLU6JjhdsTxhbU9aSI27Xcg6G6OocMMuScApuDd0Goz0nhl4ik7cPVOFyfdzZ7viztBg1nVpUzDq4EfXRH6IM=,iv:+RRJCAxHdYL5Y/MDtXBacMm7v9uc7dSBUl2uqOe+5Mw=,tag:jUA+CgznkZiqD+K0/RnN8g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
