apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:/SN4lMpUmlxr55pDC0qu81NJORYmfS5/bd2qUzyVkv6X7vnIL+56A8yEcgbjwHugCn0RKNLY2n4JIpcGm6IxDS/mZNkKndgVgmzf/nXmNcdcWdwC9mWyX2LfWAj0fPWL2bxgEHbz4VExc+fq9aJSvr+Ukf0hXH/8GpdgjavFZHMeLoxxHQgLwLgowQN0t3M3y1EvGtcQLdJI+cZQ4LYVz4bt2yHNVU78xOCljA+BQppQUjjs,iv:2FQCx1lUD14duCW5UYtsFGFRQmFyBG89aGe9/6X0NnM=,tag:wIsMdcQs8QEd7I4VYIP9Zg==,type:str]
sops:
  age:
    - recipient: age1rft6er4pj4dk7wf887pgsalekxjl6z34sc96lfkz9mkc70qxm9xqhfqhvc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzU2UzUlVIUE1Sc1JaUnNy
        TTd0ektURDg0SUk0bGswdUVWdVhPYWg4NXpvCm1UU2FPU1U4TGVCRE5SSWdBaGRY
        eVRsREc0SmxHTFVhYVFtWW1KYStoL2MKLS0tIGpYd1pmMnVaTVJxaG5tdnoyT3I3
        bFpHUU9uSUYvNkZDeUd2RGxkbE1wNUUKiMfVlP/uXbWzX3F7G1BzWqpTuSIzir5z
        VIyhLisKKnO5c4215os+bbNZWVZ6lO6bfDTURAN6BMBmpNKd9xolqw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-21T01:45:38Z"
  mac: ENC[AES256_GCM,data:URq+qhpEnwC6xZHz/zpXuDL8ZxsS1xGlGDa2G8bz7AqB+OM01jjAl0EVIWGHLzhMi4pnfOoYTPfElBKwHUWFMAMsECoHaLrH9oTeVKdj0y3StAg31K6FzNhKTOSELiFNzLduu+o3ksJ0NXR/qSmfONpxqJ+pZhMy7zw/gbmgwgU=,iv:6TzSY2GtusEzcXilYkqB/gE4RlDkAulKTEe6R4Wzs5A=,tag:gr/bmdJSWBpSVevTYyBknA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
