---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

components:
  - ../../components/sops
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./grafana/ks.yaml
  - ./prometheus/ks.yaml
  - ./prometheus-adapter/ks.yaml
  - ./blackbox-exporter/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./victoria-logs/ks.yaml
  - ./gatus/ks.yaml
  - ./unpoller/ks.yaml
