apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-credentials
stringData:
  1password-credentials.json: ENC[AES256_GCM,data:gSvx9rEXtNJAWj9RYcvWpR/2JhxZfQTA4NUo7NzHCgwA+t5+Eud/0ivkJ7dnyD/Pm4QJ8WneqIlpndVNlvieFXFRHAWHQXQ2filjwT6PgRWrweKKbGdjvL2EBvuCWUJbjBr3jHb7mrJzE5fe2dW3buVvBB1ZpcLY5VuH1CUoswde3TtKkeYLQGglYen2w2GeBnYv43v0+Cu3rX5xn6wwr5pP1EwjOEx3eW6PP/4XqxDE31qIxH0nFlQo8YRtIhBBzQFnDviR74G8FvPUR3lPgBoY2aoX8w5sYmoLonHwhMOmglf8XJCLRRyi6TBpbiRD+zVOGfzL3mklb2XFvKAINtSrYx/tXXfe/eomnu0Ar6Xtv4bM14oGeo4EEIgtahpttrNcKe2Sg2PHfxJKBJyV6PQ1Sep+9iRjTLwahKaExN0Cv2Edc3t82d08H6OwAtT7AIoHOl47wuedj1SH+tNOqn5+pcPKYxgzhP38SHEVKWkcF8mfhJjrFT2UY3udx0mOYRce37NQ/YvqtpXjWyHZB5574KU8fdMyW1yOPmtyucRwEyQj8XHMoZXLsrZmL3PrGIFJADYjSKURR5i3GDfT7qQqam3Z0/KN6KO8J19SAG6oi1nn+oRAv3N6Xs/unwaG6Eew/6yDeATkCVbMGen4RxqlyYVosWEFPkaTCe0mm1lQdslQ3Ds0v6vAH8m4krV8polEw3raCu6yRUL+hG+iCC/kuVmIaandUfggSXVBM6B5QHb5D27BYiJOT9tfYTD9Q0XuOgxK9lGhcIswWDh7kITkmF3bySTFiry4e+Z79t8q1uFCgCuAUG5FjO/cXhiJ5L/gOdrPkp5UT5iAdKdMQXF1ehKGuwMq5e0vWPRD0bGHK8svI4UGYsQeGyUC412EVkiisHiyBDnFS/BsFSyEXyB1c4s6tAbN7M2MogeT37BrA45vWt3FTWooGapynZ5HSXXGHkBUsVgEhB3x4bB5c2RmuwJbSpvt6KWkTceMlO+EbADToTGNkaRAk8yrp9so2Xnk48KAyCmFNzgPvLUOEIThT2ew1LW6QB1UACUyxTUp0iilzohWnqWJN8YYHcZ3bxs0oMWGCPntyEP0CTaXqFHZ+lN9dtZV3QXW1yCRdeM16xb7IfUfD6U/lf6nfh1MbY+nGdOCr55XW2CBd1AUQIkz4vIhzB0umXT0spEkCzAxETI44Lt50+LSoa0V4jR2rn2XSnobq/9dr27nOpLtqTTwABNd0AmUZx7jyTB/jMJ+GIWXkfVqjTibnyb+gwKwq0vPWBLyNzSO5eu1z7125UdrbDXP1AoLU4WqFofuKJZ6U27eSvPOLlUcUL7bg1LVoAYnR4ELm3+h8xHZITo6ZjqVOWbQ8Z5ZmrURhIn8ZKOxmZTFct16pZgYNv9YCOKRng4sBkQPtl8PlARyQy1TCSPn1DRybz/D6uXvAVrNGgFJQfPtvEH4pl7XspClybjY2UUMMtKzlJEjtGpqV45B+mOn1B2ekqf/IszeTdIxOn1AgtWKpMs7RUVwt/4pHcBhtV55m5101thvgwYtidPGVfUpk4Dkhn72rU9UuBEFwU9rRhoSteZtmEPBQlVFd+a4nOimtYaOy7tKNfPJfSiGhWlJnTdKsQ==,iv:kGu3AFZ5envyDWSxzwir7rOfpOe3fNETM7yFSQy6VVo=,tag:vUZptlFLzRYkEsCH+jEOOA==,type:str]
sops:
  age:
    - recipient: age1rft6er4pj4dk7wf887pgsalekxjl6z34sc96lfkz9mkc70qxm9xqhfqhvc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTTc3UjdqWW1KV1hlTElz
        eHRvanFEZzdvYjEwQ21nSjNtc1l4RkU4YndNCmtSajFjNVN6RjVocklNSTMyWERx
        YWEvUkR1R3hVL3NuQXJOaCtJMjEycDAKLS0tIGI4OUN1TFBNdzJ3V1NLZlhMdFRt
        R1FsRU9Fc3dKeE12UXVTR3F6eml2KzgKBpua0+0a3E3uuB58XNHJhRLvYAqQy0ji
        qcnlrrSamZogKmXDKOn7joxlPV5SRRY/MFVZ+xfg5U0ZtkuxyQm1hQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-19T19:48:40Z"
  mac: ENC[AES256_GCM,data:ZIe2hShICGrXfbMWFTGcLX//WEN/WGVH4D7zsSxT3qMv5lKuchkKo1d60MigP2o3jbxSt36OrhCV5hBtb/v33uen1FfqR7Yp7YeZBb3FXxeSjgj3ujoEF1mONCgrCXkCb9mMXdNLaRyG9O27NMjSlP4G1yQj1dgA1XfjHsihr1s=,iv:aWLlwyW3BeRRAHzlNv3lXV990dknhVFaMqOu3FBYOoI=,tag:n+awLtj7A73JqZW0FVwFow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
stringData:
  token: ENC[AES256_GCM,data:+8cj8Q3zh2pvb3owlO8uobIbVQ/+65m3qgRtdHsIXes8PZ6q1TYZZ5NNP6LhffpuqwGeOON/XjUvx4TB+XGO2+UpR7oZ+PoysE5Jp8Sqz5wM6Q4spkOiy4+oPfDMQyvj3+Pv0TDMpr7Us1euW4wLRIf2JZdBTyfi4CNoK4l8dTMTOJSTA1GUqTQ0W8MZzCHPmLbtBXEyI0IjBl7V6g/nOSjzb2WFvTJedRHZv0iVGAvGB+JJGF/VfNDzw+zgM1mkndMdQ4FF6ytX2WP9oKRV94MsyaoqFmkFvKyAJB0dPrVGtcmpuD5pd7/lQZ4QF9B1V0xrZLBhe1rzCG+GEFTSqKfnzm805F5Wk6zaCRIYOYHYa0I4AwroRdHdDslwG3/+Ba7OHXqxOePnLJbqLSKM5wEPL5Ac6pKpF0q/nKd+UchwHeiA/07C4dusunCkn/1l3sfMDtIRVX4yypGHOzBxRN4ernljMsYPc0BgBO7hJkRNAxH0iGqBcl0HegvM7KpTvpWoM+eLYds1ZclieVkSFqUK5xh3/8Tj850HU4xwZ6wzlNaExTjLMa7Sber65hmFbcswfsqPAqzoKpBeDT5qHWzilGnyT0hAHRkyClMMw8Y0RCUJDCFJNIOOEK68P28yx9rhhaQJ29qDWvKaGlaFz6NX/KXGuqhdtxawpJyBdUGunIDkZuZncbZiP0K1YjpThkvL/JAHLo0kmHylKfrYIzR0w78Fm7xpmVavteruCTSL/t9uAxmpNEPjRW4rWWKehppFsXVTJTqS7WbIlWMcESYeJUN9+GJuTqUfmBjcqlNKdzFO8FJvMPS2KGa5i4MOAGdsiax8Yglpr8s8FUodEgom,iv:qZVxvGezb6hS0+XRsgmPAZTqCUYIBJ5rxMKhOu6mAqA=,tag:VRq784KM+d3U+jhKzOQcBQ==,type:str]
sops:
  age:
    - recipient: age1rft6er4pj4dk7wf887pgsalekxjl6z34sc96lfkz9mkc70qxm9xqhfqhvc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTTc3UjdqWW1KV1hlTElz
        eHRvanFEZzdvYjEwQ21nSjNtc1l4RkU4YndNCmtSajFjNVN6RjVocklNSTMyWERx
        YWEvUkR1R3hVL3NuQXJOaCtJMjEycDAKLS0tIGI4OUN1TFBNdzJ3V1NLZlhMdFRt
        R1FsRU9Fc3dKeE12UXVTR3F6eml2KzgKBpua0+0a3E3uuB58XNHJhRLvYAqQy0ji
        qcnlrrSamZogKmXDKOn7joxlPV5SRRY/MFVZ+xfg5U0ZtkuxyQm1hQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-19T19:48:40Z"
  mac: ENC[AES256_GCM,data:ZIe2hShICGrXfbMWFTGcLX//WEN/WGVH4D7zsSxT3qMv5lKuchkKo1d60MigP2o3jbxSt36OrhCV5hBtb/v33uen1FfqR7Yp7YeZBb3FXxeSjgj3ujoEF1mONCgrCXkCb9mMXdNLaRyG9O27NMjSlP4G1yQj1dgA1XfjHsihr1s=,iv:aWLlwyW3BeRRAHzlNv3lXV990dknhVFaMqOu3FBYOoI=,tag:n+awLtj7A73JqZW0FVwFow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
