---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
spec:
  chartRef:
    kind: OCIRepository
    name: prometheus
  interval: 1h
  values:
    server:
      persistentVolume:
        storageClass: longhorn
    alertmanager:
      persistence:
        storageClass: longhorn
